spring:
  application:
    name: CT553_backend
  datasource:
    url: jdbc:postgresql://ct553-be-ct553.k.aivencloud.com:22066/ct553?sslmode=require
    username: avnadmin
    password: AVNS_PsfCeKl1BWSxBWjH-dj

  jpa:
    hibernate:
#      ddl-auto: update
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  jackson:
    default-property-inclusion: non_null

cloudinary:
  url: cloudinary://449763141578937:5XPkEpp24XbH8zBKGt32MeBkpds@djqcnzjbg